services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uni-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/backend-mysql"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    hostname: mysql
    container_name: uni-mysql
    image: mysql:latest
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/backend-mysql"
      SPRING_DATASOURCE_HOST: "mysql"
      SPRING_DATASOURCE_PORT: "3306"
      SPRING_DATASOURCE_ROOT_PASSWORD: "1234"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network

volumes:
  db_mysql:

networks:
  app-network:
    driver: bridge