### 배포 서버 ###

server:
  port: 8080

spring:
  application:
    name: backend

  profiles:
    include: prod

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://mysql:3306/backend-mysql
    username: root
    password: 1234

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui.path: /swagger-ui/index.html

jwt:
  expiration: 86400000
  secret: RElBUllfQU5EX0NPTU1VTklUWV9QUk9KRUNUX0RBV05BUllfQURNSU5fU0VDUkVUX0tFWQ==

logging:
  level:
    root: INFO