package inu.unithon.backend.domain.translate.repository.es.festivalContentTranslate;

import inu.unithon.backend.domain.translate.document.FestivalContentTranslateDocument;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;

public interface FestivalContentTranslateDocumentRepository extends ElasticsearchRepository<FestivalContentTranslateDocument, String>, FestivalContentTranslateDocumentRepositoryCustom {
}
